### ISSUE TITLE
Keyword + Arguments

### ISSUE THREAD

**Issue by berdon** [3kyro/caprice#1]
First, great project, I'm working on a GB emulator and this seems like the perfect repl environment for a gdb like shell.

Right now, if I setup some keywords `["load", ...]` and expect to be able to enter `load some_rom_here.rom` the space key is just ignored. Likely because it's not alphanumeric as expected by caprice/mode.rs:79. Do you have any plans on adding argument support for this type of thing?

I might submit a pull request for treating the space key as a tab and allowing additional input after a token has been completed?

**Comment by 3kyro** [comment]
Thanks for the nice words :)

Having support for arguments makes absolute sense. I wonder however what the return type should be. Right now, Caprice gets an  array of `String`s and returns a `String` to the invoking thread. If arguments are allowed, the return type should, in my opinion, follow in a type safe way the token initialization. e.g. imagine setting tokens in a form

````rust
set_tokens(&[
    "no_argument_token",
    ("one_str_argument,token", &str),
    ("two_arg_token", String, Int)
])
````
Obviously this won't be easy to express in Rust's type system, and the above code will certainly won't compile.

An even better approach would be to allow the consumer to define the type by providing a trait that has all necessary methods, something like:

````rust
pub trait Token {
    fn toToken(&str) -> Maybe Self
}
````
I would be interested in knowing your opinion on how to express such an argument return type that is not simply a String with multiple space separated tokens. 

If however you simply need a String now to advance with your project, I would happily accept a PR and publish it.

**Comment by berdon** [comment]
@3kyro 

I put some thought into this yesterday - I too much prefer type safety over ambiguity.

Your first suggestion might work with Vec's:
```rust
set_tokens([
  vec!["no_argument"],
  vec!["one_str_argument,token", ArgType::str],
  vec!["two_arg_token", ArgType::String, ArgType::u32]
])
```

I'm somewhat new to Rust, I've only been playing with it for a few weeks, but I'm not sure it has any form of runtime Type concepts. Outside of that language mechanic, we'd need some means of passing the type (such as my implied ArgType enum). It's not _exactly_ pretty but it would work fine.

The trait approach, as you say, seems nicer as it gives the caller the full control of parsing but it raises a few questions. How will we differentiate the parsing of the token itself and, therein, the handling of autocomplete on the initial token ("some_token" versus "some_other_token"). And, afterwards, the parsing of the following arguments.

That leads to a divergence in the handling of the token versus the proceeding arguments but that's probably expected. But I've spent a few minutes trying to come up with code snippets to represent such a trait and it's just not feeling right. We could have an Iterator that takes in the current buffer and returns string "tokens", we could have an Iterator of `ArgType` enums that the engine could validate the arguments against, we could just have the trait extend [From](https://doc.rust-lang.org/std/convert/trait.From.html) or [Into](https://doc.rust-lang.org/std/convert/trait.Into.html) and convert a `string` to a collection of strings. But all of that seems rather complicated.

Yesterday, prior to you responding, I made the changes to support generic arguments and, when an enter is pressed, returns, still, just a string. The caller then is required to do any splitting to coerce the string into whatever arguments they may expect.

I could see this being extended to return a:

```rust
struct TokenInput {
  token: String,
  args: Iterator // Or Vec<String>?
}
```

I think that would be pretty clean.

The nice thing about this approach is the API is left rather "clean". Arguments are left up to the consumer to validate, expect, etc. The downside is we don't handle it for the consumer.

I'll post a PR here shortly. I fixed a few bugs with the scanner buffer deviating from the terminal display which presented itself by the cursor moving past the prompt too.

**Comment by 3kyro** [comment]
First of all,  thank you for the bug squashing and the argument implementation. The approach is indeed really clean and the autocomplete function handles multi word tokens elegantly.

Regarding a more typed approach, I agree with you in general. I believe the first approach, inspired by Haskell practices, would be difficult to implement cleanly. The second could work, with several trait methods to handle the different parsing needs. But maybe that is asking too much from the consumer? Maybe a default type and implementation would help? 

Unfortunately I don't have the time right now to explore this any further, but might do so in a couple of  weeks. Are you willing to have a go nonetheless? If not I can simply publish your improvements now and revisit later.

Thanks again for the help.

**Comment by berdon** [comment]
I'm in the same boat as you - I may have some time in the coming weeks but otherwise that's why I was looking for a turnkey REPL already. :)

**Comment by 3kyro** [comment]
No problem :) Thanks for the PR
